import { hasSupabaseConfig, requireAdmin } from "@/lib/supabase/server";

export type Category = { id:string; name:string; slug:string; active:boolean; sort_order:number };
export type ProductImage = { id:string; product_id:string; storage_path:string; alt_text:string; caption:string|null; sort_order:number; is_cover:boolean; mime_type:string|null; byte_size:number|null; created_at:string };
export type Product = { id:string; name:string; slug:string; short_description:string|null; description:string|null; category_id:string; status:"draft"|"published"|"archived"; featured:boolean; product_code:string|null; sizes:string[]; color:string|null; material:string|null; collection:string|null; year:number|null; seo_title:string|null; meta_description:string|null; updated_at:string; categories?:{name:string}|null; product_images?:ProductImage[] };
export type SiteSettings = { shop_name:string; default_seo_title:string|null; default_meta_description:string|null; contact_phone:string|null; contact_email:string|null; address:string|null; working_hours:string|null; instagram_url:string|null; facebook_url:string|null; maps_url:string|null };
export type SiteContent = { hero_title:string|null; hero_description:string|null; about_title:string|null; about_content:string|null };
export type CalendarEvent = { id:string; title:string; description:string|null; start_at:string; end_at:string|null; all_day:boolean; color:string|null; status:"upcoming"|"completed"|"cancelled"; created_by:string; created_at:string; updated_at:string };
export type AppointmentRequest = { id:string; name:string; phone:string; preferred_date:string; preferred_time:string; message:string|null; product_name:string|null; status:"pending"|"confirmed"|"cancelled"; calendar_event_id:string|null; created_at:string; updated_at:string };

export async function getCategories(): Promise<Category[]> { if(!hasSupabaseConfig()) return []; const {supabase}=await requireAdmin(); const {data,error}=await supabase.from("categories").select("*").order("sort_order"); if(error) throw new Error(`Категориите не могат да бъдат заредени: ${error.message}`); return data??[]; }
export async function getProducts(searchParams?:{q?:string;status?:string;category?:string}): Promise<Product[]> { if(!hasSupabaseConfig()) return []; const {supabase}=await requireAdmin(); let q=supabase.from("products").select("*,categories(name),product_images(id,product_id,storage_path,alt_text,caption,sort_order,is_cover,mime_type,byte_size,created_at)").order("updated_at",{ascending:false}).order("sort_order",{referencedTable:"product_images",ascending:true}).limit(100); if(searchParams?.q) q=q.ilike("name",`%${searchParams.q}%`); if(searchParams?.status) q=q.eq("status",searchParams.status); if(searchParams?.category) q=q.eq("category_id",searchParams.category); const {data,error}=await q; if(error) throw new Error(`Продуктите не могат да бъдат заредени: ${error.message}`); return (data??[]) as Product[]; }
export async function getProduct(id:string):Promise<Product|null>{ if(!hasSupabaseConfig()) return null; const {supabase}=await requireAdmin(); const {data,error}=await supabase.from("products").select("*,categories(name),product_images(*)").eq("id",id).order("sort_order",{referencedTable:"product_images",ascending:true}).maybeSingle(); if(error) throw new Error(`Продуктът не може да бъде зареден: ${error.message}`); return data as Product|null; }
export async function getSiteSettings():Promise<SiteSettings>{const fallback:SiteSettings={shop_name:"Емоция",default_seo_title:null,default_meta_description:null,contact_phone:null,contact_email:null,address:null,working_hours:null,instagram_url:null,facebook_url:null,maps_url:null};if(!hasSupabaseConfig())return fallback;const{supabase}=await requireAdmin();const{data,error}=await supabase.from("site_settings").select("shop_name,default_seo_title,default_meta_description,contact_phone,contact_email,address,working_hours,instagram_url,facebook_url,maps_url").eq("id",true).maybeSingle();if(error)throw new Error(`Настройките не могат да бъдат заредени: ${error.message}`);return data??fallback;}
export async function getSiteContent():Promise<SiteContent>{const fallback:SiteContent={hero_title:null,hero_description:null,about_title:null,about_content:null};if(!hasSupabaseConfig())return fallback;const{supabase}=await requireAdmin();const{data,error}=await supabase.from("site_content").select("hero_title,hero_description,about_title,about_content").eq("id",true).maybeSingle();if(error)throw new Error(`Съдържанието не може да бъде заредено: ${error.message}`);return data??fallback;}
export async function getCalendarEvents(start:string,end:string):Promise<CalendarEvent[]>{if(!hasSupabaseConfig())return[];const{supabase}=await requireAdmin();const{data,error}=await supabase.from("calendar_events").select("*").gte("start_at",start).lt("start_at",end).order("start_at");if(error){if(error.code==="42P01"||error.code==="PGRST205")throw new Error("Календарът изисква Supabase migration.");throw new Error(`Събитията не могат да бъдат заредени: ${error.message}`);}return(data??[])as CalendarEvent[];}
export async function getAppointmentRequests():Promise<AppointmentRequest[]>{if(!hasSupabaseConfig())return[];const{supabase}=await requireAdmin();const{data,error}=await supabase.from("appointment_requests").select("*").eq("status","pending").order("preferred_date").order("preferred_time").limit(50);if(error){if(error.code==="42P01"||error.code==="PGRST205")throw new Error("Заявките за проба изискват Supabase migration.");throw new Error(`Заявките не могат да бъдат заредени: ${error.message}`);}return(data??[])as AppointmentRequest[];}
